# テンソル

テンソルは、NDArray（Numpy 配列）で表現される、データの入れ物。
格納されるのは基本的に数値データ。

行列を任意の数の次元に対して一般化したものであり、
ベクトル（1 次元配列）は 1 階テンソル、行列（2 次元配列）は 2 階テンソルという。




## Numpy のスカラー（0階テンソル）

数値を 1 つしか格納していないテンソルは、スカラーと呼ばれる。
0 階テンソルや、スカラーテンソルと呼ばれることもある。

In [1]:
import numpy as np

# 0階テンソルを生成
scalar = np.array(15)

# 出力
print(scalar)
# データ型の出力
print(scalar.dtype)
# 次元数の出力
print(scalar.ndim)

15
int64
0


## Numpy のベクトル（1階テンソル）

線形代数では、「要素を縦または横に一列に並べたもの」をベクトルと呼ぶ。
これは Numpy の1次元配列なので、1階テンソル。

In [ ]:
vector = np.array([1, 2, 3])

# 出力
print(vector)
# データ型の出力
print(vector.dtype)
# 次元数の出力
print(vector.ndim)

# ベクトルの要素を参照
print(vector[1])

# ベクトルの要素を変更
vector[2] = 100
print(vector)

[1 2 3]
int64
1
2
[  1   2 100]


## Numpy の行列（2階テンソル）

Numpy の2次元配列は行列。
すなわち2階テンソル。

In [16]:
matrix = np.array(
    [
        [10, 15, 20, 25, 30],
        [20, 30, 40, 50, 60],
        [50, 53, 56, 59, 62],
    ]
)

# 出力
print(matrix)
# データ型の出力
print(matrix.dtype)
# 次元数の出力
print(matrix.ndim)

# 行列の形状を出力
print(matrix.shape)

[[10 15 20 25 30]
 [20 30 40 50 60]
 [50 53 56 59 62]]
int64
2
(3, 5)


## 3階テンソルとより高階数のテンソル

複数の行列を格納したものは、3階テンソル。


3階テンソルをまとめて4階テンソルを作ることも可能。
一般的にデータ分析や機械学習で扱うのは3階テンソルまでが多いが、
機械学習でカラー画像を扱う場合は4階テンソル、動画データを扱う場合は5階テンソルを使用することがある。

In [19]:
matrix = np.array(
    [
        [
            [10, 15, 20, 25, 30],
            [20, 30, 40, 50, 60],
            [50, 53, 56, 59, 62],
        ],
        [
            [10, 15, 20, 25, 30],
            [20, 30, 40, 50, 60],
            [50, 53, 56, 59, 62],
        ],
        [
            [10, 15, 20, 25, 30],
            [20, 30, 40, 50, 60],
            [50, 53, 56, 59, 62],
        ],
    ]
)

# 出力
print(matrix)
# データ型の出力
print(matrix.dtype)
# 次元数の出力
print(matrix.ndim)

# 行列の形状を出力
print(matrix.shape)

[[[10 15 20 25 30]
  [20 30 40 50 60]
  [50 53 56 59 62]]

 [[10 15 20 25 30]
  [20 30 40 50 60]
  [50 53 56 59 62]]

 [[10 15 20 25 30]
  [20 30 40 50 60]
  [50 53 56 59 62]]]
int64
3
(3, 3, 5)
