# ベクトルの演算

Numpy の1次元配列はベクトル（1階テンソル）である。

ベクトルは、それぞれの要素数が同じであれば、それぞれの要素同士の演算ができる。
ここではベクトルの演算を行う。

In [2]:
import numpy as np

x1 = np.array([1, 2, 3])
y1 = np.array([4, 5, 6])

# ベクトル要素同士の加算
print(x1 + y1)

# ベクトル要素同士の減算
print(x1 - y1)

# ベクトル要素同士の掛け算
print(x1 * y1)

# ベクトル要素同士の割り算
print(x1 / y1)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## ベクトルのスカラー演算

数値を1つしか含まない0階テンソルをスカラーというが、  
線形代数では、「大きさのみで表され、方向を持たない量」をスカラーという  

Python のリストは1次元配列であり、全ての要素に同じ数を加えたり2倍にするような場合は、  
for ループなどで処理を回す必要がある。  
それに対して、Numpy の1次元配列であるベクトルは、for ループを使わずに一括処理が行える。  
これは Numpy のブロードキャストと呼ばれる仕組みによって実現されている。  
ベクトルに対して四則演算子でスカラー演算を行うと、全ての要素に対して演算が行われる。

In [3]:
# データ型を指定して、ベクトルを作成
x2 = np.array([1, 2, 3, 4, 5], dtype=float)
# 0階テンソル（スカラーテンソル）を作成
y2 = np.array(10)

# ベクトルに対してスカラーテンソルを加算
print(x2 + y2)

# ベクトルに対してスカラーテンソルで減算
print(x2 - y2)

# ベクトルに対してスカラーテンソルを掛け算
print(x2 * y2)

# ベクトルに対してスカラーテンソルで割り算
print(x2 / y2)

[11. 12. 13. 14. 15.]
[-9. -8. -7. -6. -5.]
[10. 20. 30. 40. 50.]
[0.1 0.2 0.3 0.4 0.5]


## ベクトル同士の四則演算

ベクトル同士を四則演算しで演算すると、同じ次元の要素同士の演算が行われる。

In [4]:
vec1 = np.array([10, 20, 30])
vec2 = np.array([40, 50, 60])

# ベクトル要素同士の加算
print(vec1 + vec2)

# ベクトル要素同士の減算
print(vec1 - vec2)

# ベクトル要素同士の掛け算
print(vec1 * vec2)

# ベクトル要素同士の割り算
print(vec1 / vec2)

# ベクトルの定数倍
print(vec1 * 4)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]
[ 40  80 120]


## ベクトルのアダマール積

要素の数が同じベクトル同士を掛け算すると、要素同士が掛け算される。
これをベクトルのアダマール積という。

In [9]:
print(vec1 * vec2)

[ 400 1000 1800]


## ベクトルの内積

ベクトル同士の要素の席を内積という。
ベクトル a と b の内積は、真ん中に「・」を入れ、$a ・ b$ と表す

$a = \begin{pmatrix}2 \\ 3 \end{pmatrix}$ と $b = \begin{pmatrix}4 \\ 5 \end{pmatrix}$ の内積は、  
$a・b = \begin{pmatrix}2 \\ 3 \end{pmatrix}・\begin{pmatrix}4 \\ 5 \end{pmatrix}$ となり  
$2・4 + 3・5 = 23$  
のように、第1成分同士、第2成分同士を掛けて和を求める。


In [7]:
vector1 = np.array([2, 3])
vector2 = np.array([4, 5])

# vector1 と vector2 の内積を求める
np.dot(vector1, vector2)

23