# 行列の計算

Numpy の2次元配列で行列を表現できる。  
行列は行と列の2つの軸を持つため、2階テンソルとなる。  

ここでは、線形代数の基本に基づき、行列の演算方法のうちデータサイエンスで必要になる部分のみをみていく。

# 行列の構造

$a = \begin{pmatrix} \ \ 1 \ \ \ 5 \\ 10 \ 15 \end{pmatrix}$

$b = \begin{pmatrix} 1 \ 5 \ 7 \\ 8 \ 3 \ 9 \end{pmatrix}$

このように、（）の中に数を並べると、それが行列になる。  
横の並びを「`行`」、縦の並びを「`列`」と呼ぶ。  
$a$ は2行2列、$b$ は2行3列の行列である。  

縦に並んだ行の数と横に並んだ列の数が同じとき、`正方行列` という。

### 行列の中身は「`成分`」という

$\begin{pmatrix} 2 \ 1 \ 6 \\ 4 \ 7 \ 5 \\ 5 \ 2 \ 9 \end{pmatrix}$

上記行列で、1行目3列目の「6」は、「`第1行、第3列の成分`」という。

# 行ベクトルや列ベクトルの形をした行列

数学には、数字の組を表す「ベクトル」がある。
数学のベクトルは、次のように数字の組が1行、または1列のどちらかだけになる。

$c = \begin{pmatrix} 5 \ 8 \ 2 \ 6 \end{pmatrix}$

$d = \begin{pmatrix} 3 \\ 5 \\ 4 \end{pmatrix}$

$c$ は行ベクトルであり、1行4列の行列でもある。  
$d$ は列ベクトルであり、3行1列の行列でもある。


# Numpy では多次元配列で行列を表現する

In [1]:
import numpy as np

# 3行3列の行列を作成
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    dtype=float,
)

print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 行列のスカラー演算

ベクトルと同様に、行列に対してスカラー演算を行うと、  
行列のすべての成分に対して演算が行われる。

In [2]:
# スカラー演算（加算）
print(matrix + 10)

# スカラー演算（減算）
print(matrix - 10)

# スカラー演算（乗算）、定数倍ともいう
print(matrix * 2)

# スカラー演算（除算）
print(matrix / 2)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]
[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


# 行列の成分へのアクセス

行列の成分（要素）にアクセスするには、リストと同様にブラケット `[]` を使用して以下のように指定する。

`[行開始インデックス : 行終了インデックス, 列開始インデックス : 列終了インデックス]`

In [11]:
matrix2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

print(matrix2.dtype)

# 第1行の全ての成分を出力
print(matrix2[0])
print(matrix2[0,])

# 第1列の全ての成分を出力
print(matrix2[:, 0])

# 2行2列の成分を出力
print(matrix2[1, 1])

# 1行 ～ 2行、1列 ～ 2列の部分行列を抽出
print(matrix2[0:2, 0:2])

int64
[1 2 3]
[1 2 3]
[1 4 7]
5
[[1 2]
 [4 5]]


# 行列の成分同士の加算・減算

行列に対してスカラー演算を行うと、ブロードキャストの仕組みにより、  
すべての成分に同じ演算が適用される。

$A = \begin{pmatrix} 1 \ 2 \\ 3 \ 4 \end{pmatrix}$

$B = \begin{pmatrix} 4 \ 3 \\ 2 \ 1 \end{pmatrix}$

上記の行列 A・B があるとする。

A と B の足し算は以下のようになる。

$A + B = \begin{pmatrix} 1 \ 2 \\ 3 \ 4 \end{pmatrix} + \begin{pmatrix} 4 \ 3 \\ 2 \ 1 \end{pmatrix} = \begin{pmatrix} 1 + 4 \ \ \ 2 + 3 \\ 3 + 2 \ \ \ 4 + 1 \end{pmatrix} = \begin{pmatrix} 5 \ 5 \\ 5 \ 5 \end{pmatrix}$

A と B の引き算は以下のようになる。

$A - B = \begin{pmatrix} 1 \ 2 \\ 3 \ 4 \end{pmatrix} - \begin{pmatrix} 4 \ 3 \\ 2 \ 1 \end{pmatrix} = \begin{pmatrix} 1 - 4 \ \ \ 2 - 3 \\ 3 - 2 \ \ \ 4 - 1 \end{pmatrix} = \begin{pmatrix} -3 \ \ \ -1 \\ \ 1 \ \ \ \ \ \ \ 3 \end{pmatrix}$

このように、行列の足し算と引き算は、「同じ行と列の成分同士を足し算または引き算」する。

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

# 成分同士の足し算
print(a + b)
# 成分同士の引き算
print(a - b)

[5 5 5 5]
[-3 -1  1  3]


# 行列のアダマール積

行列の成分ごとの積を、行列のアダマール積という。

In [14]:
print(a * b)

# 行列のアダマール積では、行列の形状が異なっていても、ブロードキャストの要件を満たせば計算が可能
c = np.array(
    [
        [1],
        [2],
    ]
)
d = np.array(
    [
        [
            1,
            2,
        ],
        [
            3,
            4,
        ],
    ]
)

print(c * d)

[4 6 6 4]
[[1 2]
 [6 8]]


# 行列の内積

内積の計算は「行の順番の数と、列の順番の数が同じ成分同士を掛けて、足し上げる」こと。


以下の横ベクトルと縦ベクトルの内積は、それぞれ(1, 2)行列、(2, 1)行列とみなして計算を行う必要がある

$\begin{pmatrix} 2 \ 3 \end{pmatrix} \begin{pmatrix} 4 \\ 5 \end{pmatrix} = 2・4 + 3・5 = 23$

次に、(1, 2)行列と(2, 2)行列の内積の場合

$\begin{pmatrix} 1 \ 2 \end{pmatrix} \begin{pmatrix} 3 \ 4 \\ 5 \ 6 \end{pmatrix} = (1・3 + 2・5\ \ \ \ 1・4 + 2・6) = (13\ \ 16)$

次に、(2, 2)行列と(2, 2)行列同士の内積

$\begin{pmatrix} 1 \ 2 \\ 3 \ 4 \end{pmatrix} \begin{pmatrix} 5 \ 6 \\ 7 \ 8 \end{pmatrix} = \begin{pmatrix}1・5 + 2・7 \ \ \ \ \ 3・5 + 4・7 \\ 1・6 + 2・8 \ \ \ \ \ 3・6 + 4・8\end{pmatrix} = \begin{pmatrix} 19 \ 22 \\ 43 \ 50 \end{pmatrix}$

In [15]:
m1 = np.array([[1, 2], [3, 4]])

m2 = np.array([[5, 6], [7, 8]])

# (2, 2)行列同士の内積を求める
np.dot(m1, m2)

array([[19, 22],
       [43, 50]])

# 行と列を入れ替えて「転置行列」を作る

行列の行と列を入れ替えたものを `転置行列` という。

$A = \begin{pmatrix} 1 \ 2 \ 3 \\ 4 \ 5 \ 6 \end{pmatrix}$

のとき、転置行列 $^t\!A$ は以下のようになる。

$^t\!A = \begin{pmatrix} 1 \ 4 \\ 2 \ 5 \\ 3 \ 6 \end{pmatrix}$


In [18]:
mt = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

# transpose で転置行列を求める
print(np.transpose(mt))

# NDArray の T でも転置行列を求められる
print(mt.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
