# 行列の計算

Numpy の2次元配列で行列を表現できる。  
行列は行と列の2つの軸を持つため、2階テンソルとなる。  

ここでは、線形代数の基本に基づき、行列の演算方法のうちデータサイエンスで必要になる部分のみをみていく。

# 行列の構造

$a = \begin{pmatrix} \ \ 1 \ \ \ 5 \\ 10 \ 15 \end{pmatrix}$

$b = \begin{pmatrix} 1 \ 5 \ 7 \\ 8 \ 3 \ 9 \end{pmatrix}$

このように、（）の中に数を並べると、それが行列になる。  
横の並びを「`行`」、縦の並びを「`列`」と呼ぶ。  
$a$ は2行2列、$b$ は2行3列の行列である。  

縦に並んだ行の数と横に並んだ列の数が同じとき、`正方行列` という。

### 行列の中身は「`成分`」という

$\begin{pmatrix} 2 \ 1 \ 6 \\ 4 \ 7 \ 5 \\ 5 \ 2 \ 9 \end{pmatrix}$

上記行列で、1行目3列目の「6」は、「`第1行、第3列の成分`」という。

# 行ベクトルや列ベクトルの形をした行列

数学には、数字の組を表す「ベクトル」がある。
数学のベクトルは、次のように数字の組が1行、または1列のどちらかだけになる。

$c = \begin{pmatrix} 5 \ 8 \ 2 \ 6 \end{pmatrix}$

$d = \begin{pmatrix} 3 \\ 5 \\ 4 \end{pmatrix}$

$c$ は行ベクトルであり、1行4列の行列でもある。  
$d$ は列ベクトルであり、3行1列の行列でもある。


# Numpy では多次元配列で行列を表現する

In [1]:
import numpy as np

# 3行3列の行列を作成
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    dtype=float,
)

print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 行列のスカラー演算

ベクトルと同様に、行列に対してスカラー演算を行うと、  
行列のすべての成分に対して演算が行われる。

In [6]:
# スカラー演算（加算）
print(matrix + 10)

# スカラー演算（減算）
print(matrix - 10)

# スカラー演算（乗算）、定数倍ともいう
print(matrix * 2)

# スカラー演算（除算）
print(matrix / 2)


[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]
[[-9. -8. -7.]
 [-6. -5. -4.]
 [-3. -2. -1.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


# 行列の成分へのアクセス

行列の成分（要素）にアクセスするには、リストと同様にブラケット `[]` を使用して以下のように指定する。

`[行開始インデックス : 行終了インデックス, 列開始インデックス : 列終了インデックス]`